# Comment below when testing and uncomment app properties
spring:
  datasource:
    url: jdbc:sqlserver://parenthivesqlserver.database.windows.net:1433;database=ParentHiveDataBase;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ParentHiveAdmin
    password: Parenthive123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080



